In [1]:
import numpy as np
import pandas as pd

In [40]:
df = pd.read_csv("data/survey_results_public.csv", index_col="Respondent")
schema_df = pd.read_csv("data/survey_results_schema.csv", index_col="Column")

In [39]:
df

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,...,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,...,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time",...,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,...,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,...,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,...,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88377,NaN,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,...,Man,No,NaN,NaN,No,Appropriate in length,Easy
88601,NaN,No,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88863,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time",...,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

In [41]:
schema_df

                                                   QuestionText
Column
Respondent    Randomized respondent ID number (not in order ...
MainBranch    Which of the following options best describes ...
Hobbyist                                Do you code as a hobby?
OpenSourcer         How often do you contribute to open source?
OpenSource    How do you feel about the quality of open sour...
...                                                         ...
Sexuality     Which of the following do you currently identi...
Ethnicity     Which of the following do you identify as? Ple...
Dependents    Do you have any dependents (e.g., children, el...
SurveyLength  How do you feel about the length of the survey...
SurveyEase    How easy or difficult was this survey to compl...

[85 rows x 1 columns]

In [47]:
schema_df.loc["MgrIdiot", "QuestionText"]

'How confident are you that your manager knows what theyâ€™re doing?'

In [50]:
demo_df = pd.read_csv("data/Fortune_10.csv")
demo_df

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Unnamed: 7
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,NaN
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,NaN
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,NaN
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,NaN
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,NaN
5,6,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,NaN
6,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,NaN
7,8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,NaN
8,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,NaN
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,NaN